### ISSUE TITLE
Suggestion: Alternative to use a password in code

### ISSUE THREAD

**Issue by Bartmax** [Crypto-Spartan/unifi-search-tool#1]
Suggestion:
There are 2 ways I think would be better than settings user/pass on code.
You can use args and/or make use of environment variables.

Reading args or an enviroment variable for user/password would be a better recommendation, with the added benefit no need to re build / modify code to update credentials.

**Comment by Crypto-Spartan** [comment]
Adding the credentials to the code will only pre-populate the fields. This is in no way mandatory. It just helps to speed up the process if you launch the tool frequently, you won't have to re-type the same information in again.

For our use case at the company I work for, we just pre-populate the url and nothing else.

**Comment by Crypto-Spartan** [comment]
I have an idea - what if I add a prepopulate.conf file, and people can write their information to that and save the file. The executable will then read the file on launch to determine if any of the fields have info to pre-populate. Thoughts?

**Comment by Crypto-Spartan** [comment]
@Bartmax this has been addressed in [v.1.4.0](https://github.com/Crypto-Spartan/unifi-search-tool/releases/tag/1.4.0)
