### ISSUE TITLE
Error parsing Json

### ISSUE THREAD

**Issue by as400442** [Crypto-Spartan/unifi-search-tool#33]
Running latest build on W11
Confirmed correct URL, Creds and MAC Address

Error below.
```
Error parsing json from
https://unifi.fastnet.me:8443/api/s/gyc/stat/device-basic
Serde("missing field `in_gateway_mode`") at character 0
```

**Comment by Crypto-Spartan** [comment]
Can you provide the version of the Unifi Controller?

**Comment by Crypto-Spartan** [comment]
I can confirm that this is an issue I will need to fix, definitely not something on your end.

**Comment by as400442** [comment]
> Can you provide the version of the Unifi Controller?
> 
> I can confirm that this is an issue I will need to fix, definitely not something on your end. Thank you for the bug report!

Network 7.1.66

**Comment by Crypto-Spartan** [comment]
Thank you!

This wasn't what I expected, I figured it'd be a newer controller version that caused this. As far as I knew, all devices that came back under the `/api/s/{site_code}/stat/device-basic` contained the `in_gateway_mode` field. Would you be willing to share the list of devices that is in this Unifi site? (can be via email if you don't want to share it here but are still willing to share it, can reach me via info@cryptospartan.net) I wonder if there's a specific Ubiquiti device/model that they haven't properly configured the values for in the API.

Regardless, I should have a fix for this pretty soon.

**Comment by Crypto-Spartan** [comment]
Fixed in [v2.2.3](https://github.com/Crypto-Spartan/unifi-search-tool/releases/tag/v2.2.3)

**Comment by as400442** [comment]
Hello,
Gladly, ill need to export it at the office tomorrow and ill shoot you a list over email.
It is a massive multi-site several hundred device controller.

Sent from Mail for Windows

**Comment by as400442** [comment]
Amazing!

Thank you.

Sent from Mail for Windows

**Comment by Crypto-Spartan** [comment]
I'm only looking for the device list out of one specific Unifi Site, I don't need the entire controller. But thank you!

**Comment by as400442** [comment]
Ok
UAP-AC-Lite
UAP-AC-M-Pro
UAP-AC-M
USG-3P
US-16-150W
US-8

**Comment by Crypto-Spartan** [comment]
@as400442 Thank you!

Okay, I have 1 final ask, I promise. After you've logged into the controller, can you open another browser tab and go to https://unifi.fastnet.me:8443/api/s/gyc/stat/device-basic. I'd love to see that json blob.

**Comment by as400442** [comment]
Gladly, I have sent this to your email.

**Comment by Crypto-Spartan** [comment]
I unfortunately did not receive any emails

**Comment by as400442** [comment]
Looks like I got stuck in a spam filter.
See below:

{
  "meta": {
    "rc": "ok"
  },
  "data": [
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "uap",
      "model": "U7LT",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "usw",
      "model": "US16P150"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "ugw",
      "model": "UGW3",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "uap",
      "model": "U7LT",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "uap",
      "model": "U7MP",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "uap",
      "model": "U7MSH",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "uap",
      "model": "U7LT",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "uap",
      "model": "U7MP",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "uap",
      "model": "U7LT",
      "name": "[redacted]"
    },
    {
      "mac": "[redacted]",
      "state": 0,
      "adopted": true,
      "disabled": false,
      "type": "usw",
      "model": "US8"
    }
  ]
}
________________________________

**Comment by Crypto-Spartan** [comment]
Thank you!!!
