### ISSUE TITLE
Unable to use tool with 2FA accounts

### ISSUE THREAD

**Issue by zaidelancestonit** [Crypto-Spartan/unifi-search-tool#34]
When trying to sign in with a UI account with 2FA enabled, it gives an "Invalid Credentials" error
![image](https://github.com/user-attachments/assets/eaaf3484-2db3-414b-b35c-c0f0d5ad89c0)

**Comment by Crypto-Spartan** [comment]
Please see #18.

I only support logging in to the Unifi Controller with local credentials. I don't have a way to authenticate with Ubiquiti's 2FA.
