### ISSUE TITLE
Can't login need input 2FA

### ISSUE THREAD

**Issue by nurrokhaini** [Crypto-Spartan/unifi-search-tool#35]
Since unifi force mandatory to use 2FA token when login, how possible to use this tools ?
because every login to controller need input token

**Comment by Crypto-Spartan** [comment]
Are you logging in via ui.com or are you logging in to the controller instance itself?

**Comment by Crypto-Spartan** [comment]
I don't really have a way to handle Authentication with Ubiquiti's 2FA, I'm not so sure it's possible to support it even if I wanted to

**Comment by Crypto-Spartan** [comment]
Closing since no response
